### ISSUE TITLE
Add badges to README

### ISSUE THREAD

**Issue by xwu0226** [IBM/MAX-Named-Entity-Tagger#6]

**Comment by ajbozarth** [comment]
Is there a purpose to the PR? I already have a PR open for this

**Comment by gdequeiroz** [comment]
Can we close this @xwu0226 @ajbozarth?

**Comment by ajbozarth** [comment]
I think this may have been opened by Wrike

**Comment by xwu0226** [comment]
yeah. When a PR is created in GHE, it synchs to wrike as a task. When the task is created in Wrike, writes does not know this is a PR and synch back to GHE as an issue. This is a bad design in Unito synch tool for Wrike.
